### ISSUE TITLE
Bug: CLI crashes after update

### ISSUE THREAD

**Issue by atimin** [reductstore/reduct-cli-py#67]
### What happened?

After update to 0.9.0 version, the CLI stopped exporting data:

```
 rcli export bucket  local/datasets local/datasets1 --entries=cats
[AttributeError] 'pydantic_core._pydantic_core.Url' object has no attribute 'rstrip'
Aborted!
```

### Version

0.9.0

### OS

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
